#!/usr/bin/env ruby
require_relative 'lib/word_squares'
require_relative 'lib/pivot_word_squares'
require_relative 'lib/base_word_squares'

if ARGV[0].nil?
  printf "Usage: \n\tone_word_square <size>\n"
  exit
end
size = ARGV[0].to_i

@ws = WordSquares.new('word_list')
@word_square = []
strategy = ARGV[1]

def time_generation(dimension,strategy)
  puts "Generating #{dimension}-square with strategy #{strategy}"
  start = Time.now
  strategy = Kernel.const_get(strategy)
@word_square = @ws.generate(dimension,strategy)
  stop = Time.now
  puts "This word square:"
  puts @word_square
  puts "took #{stop - start} seconds to generate"
  end

puts "Generating word square of size #{size}"
puts Time.now.strftime("%c")
time_generation(size,strategy)
puts Time.now.strftime("%c")
